/*
Copyright (C) 2025 Nethesis S.r.l.
SPDX-License-Identifier: AGPL-3.0-or-later
*/

package methods

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/gin-gonic/gin/binding"

	"github.com/nethesis/my/backend/cache"
	"github.com/nethesis/my/backend/entities"
	"github.com/nethesis/my/backend/helpers"
	"github.com/nethesis/my/backend/logger"
	"github.com/nethesis/my/backend/models"
	"github.com/nethesis/my/backend/response"
	"github.com/nethesis/my/backend/services/local"
)

// denyOwnerOrgTargetWithoutOwnerRole answers 403 and returns true when the
// target user belongs to the Owner organization and the caller lacks the Owner
// user role. Every Owner-organization member shares the same org role, so
// managing that membership (delete/suspend/reactivate/password reset) keys on
// the technical role, not on the organization role. Fail-closed: an org type
// the partner tables cannot vouch for (lookup error included) is treated as
// the Owner organization.
func denyOwnerOrgTargetWithoutOwnerRole(c *gin.Context, user *models.User, targetOrgID string) bool {
	if targetOrgID == "" {
		return false
	}
	if models.IsPartnerOrgType(local.NewUserService().GetOrganizationType(targetOrgID)) {
		return false
	}
	if models.HasOwnerUserRole(user.UserRoles) {
		return false
	}
	c.JSON(http.StatusForbidden, response.Forbidden("access denied: only the Owner role can manage users of the Owner organization", nil))
	return true
}

// invalidateUserProfileCache removes the cached user profile from Redis.
// This ensures that changes to roles, permissions, or profile data take effect immediately.
func invalidateUserProfileCache(logtoID *string) {
	if logtoID == nil {
		return
	}
	local.InvalidateUserProfileCache(*logtoID)
}

// CreateUser handles POST /api/users - creates a new user locally and syncs to Logto
func CreateUser(c *gin.Context) {
	// Parse request body
	var request models.CreateLocalUserRequest
	if err := c.ShouldBindBodyWith(&request, binding.JSON); err != nil {
		c.JSON(http.StatusBadRequest, response.ValidationBadRequestMultiple(err))
		return
	}

	// Password will be auto-generated by the service

	// Validate that at least one role is assigned
	if len(request.UserRoleIDs) == 0 {
		c.JSON(http.StatusBadRequest, response.ValidationFailed("validation failed", []response.ValidationError{
			{Key: "user_role_ids", Message: "at least one role is required"},
		}))
		return
	}

	// Get current user context
	user, ok := helpers.GetUserFromContext(c)
	if !ok {
		return
	}

	// Create service
	service := local.NewUserService()

	// Validate permissions
	userOrgRole := strings.ToLower(user.OrgRole)
	if canCreate, reason := service.CanCreateUser(userOrgRole, user.OrganizationID, &request); !canCreate {
		c.JSON(http.StatusForbidden, response.Forbidden("access denied: "+reason, nil))
		return
	}

	// Validate role assignment permissions if roles are being assigned
	if len(request.UserRoleIDs) > 0 {
		roleCache := cache.GetRoleNames()
		if !roleCache.IsLoaded() {
			logger.Error().
				Str("current_user_id", user.ID).
				Msg("Role cache not loaded - cannot validate role assignments")
			c.JSON(http.StatusInternalServerError, response.InternalServerError("role validation unavailable", nil))
			return
		}

		// Check each role being assigned
		for _, roleID := range request.UserRoleIDs {
			// Reject unknown roles up front so creation never starts with a role
			// that does not exist (which would otherwise fail mid-sync in Logto).
			if !roleCache.HasRole(roleID) {
				c.JSON(http.StatusBadRequest, response.ValidationFailed("validation failed", []response.ValidationError{
					{Key: "user_role_ids", Message: "role not found", Value: roleID},
				}))
				return
			}

			accessControl, exists := roleCache.GetAccessControl(roleID)
			if exists && accessControl.HasAccessControl {
				// This role has access control restrictions
				hasPermission := HasOrgRolePermission(user.OrgRole, accessControl.RequiredOrgRole)
				if !hasPermission {
					logger.RequestLogger(c, "users").Warn().
						Str("operation", "role_assignment_denied").
						Str("current_user_id", user.ID).
						Str("current_user_org_role", user.OrgRole).
						Str("role_id", roleID).
						Str("required_org_role", accessControl.RequiredOrgRole).
						Msg("User attempted to assign role without sufficient privileges")

					c.JSON(http.StatusForbidden, response.Forbidden("insufficient privileges to assign this role", map[string]interface{}{
						"role_id":           roleID,
						"required_org_role": strings.ToLower(accessControl.RequiredOrgRole),
						"current_org_role":  strings.ToLower(user.OrgRole),
					}))
					return
				}

				logger.RequestLogger(c, "users").Debug().
					Str("operation", "role_assignment_validated").
					Str("current_user_id", user.ID).
					Str("current_user_org_role", user.OrgRole).
					Str("role_id", roleID).
					Str("required_org_role", accessControl.RequiredOrgRole).
					Msg("Role assignment validated successfully")
			}
		}
	}

	// Create user
	account, err := service.CreateUser(&request, models.NewOrgCreatorFromUser(*user), user.OrganizationID, user.UserRoles)
	if err != nil {
		// Check if it's a validation error from service
		if validationErr := getValidationError(err); validationErr != nil {
			logger.Warn().
				Str("user_id", user.ID).
				Str("user_username", request.Username).
				Str("validation_reason", validationErr.ErrorData.Errors[0].Message).
				Msg("User creation validation failed")

			// An authorization refusal from the service (Owner-organization
			// membership is an Owner-role exclusive) is a 403, not a 400.
			if validationErr.StatusCode == http.StatusForbidden {
				c.JSON(http.StatusForbidden, response.Forbidden("access denied: "+validationErr.ErrorData.Errors[0].Message, nil))
				return
			}
			c.JSON(http.StatusBadRequest, response.ValidationFailed("validation failed", validationErr.ErrorData.Errors))
			return
		}

		// System error - log as error
		logger.Error().
			Err(err).
			Str("user_id", user.ID).
			Str("user_username", request.Username).
			Msg("Failed to create user")

		// Default to internal server error
		c.JSON(http.StatusInternalServerError, response.InternalServerError("failed to create user", map[string]interface{}{
			"error": err.Error(),
		}))
		return
	}

	// Log the action
	logger.LogBusinessOperation(c, "users", "create", "user", account.ID, true, nil)

	// Return success response
	c.JSON(http.StatusCreated, response.Created("user created successfully", account))
}

// GetUser handles GET /api/users/:id - retrieves a single user account
func GetUser(c *gin.Context) {
	// Get user ID from URL parameter
	userID := c.Param("id")
	if userID == "" {
		c.JSON(http.StatusBadRequest, response.BadRequest("user ID required", nil))
		return
	}

	// Get current user context
	user, ok := helpers.GetUserFromContext(c)
	if !ok {
		return
	}

	// Get user account
	repo := entities.NewLocalUserRepository()
	account, err := repo.GetByID(userID)
	if err != nil {
		if strings.Contains(err.Error(), "not found") {
			c.JSON(http.StatusNotFound, response.NotFound("user not found", nil))
			return
		}

		logger.Error().
			Err(err).
			Str("current_user_id", user.ID).
			Str("target_user_id", userID).
			Msg("Failed to get user")

		c.JSON(http.StatusInternalServerError, response.InternalServerError("failed to get user", nil))
		return
	}

	// Apply RBAC validation. The :id parameter is a logto_id, so self-access is
	// decided against the caller's LogtoID — user.ID is the local database id and
	// would never match.
	userOrgRole := strings.ToLower(user.OrgRole)
	isSelf := userID == user.ID || (user.LogtoID != nil && userID == *user.LogtoID)

	if !isSelf {
		targetOrgID := ""
		if account.OrganizationID != nil {
			targetOrgID = *account.OrganizationID
		}

		service := local.NewUserService()
		if canRead, reason := service.CanReadUser(userOrgRole, user.OrganizationID, targetOrgID); !canRead {
			c.JSON(http.StatusForbidden, response.Forbidden("access denied: "+reason, nil))
			return
		}
	}

	// Log the action
	logger.RequestLogger(c, "users").Info().
		Str("operation", "get_user").
		Str("user_id", userID).
		Msg("User details requested")

	// Return user account
	c.JSON(http.StatusOK, response.OK("user retrieved successfully", account))
}

// GetUsers handles GET /api/users - list accounts with pagination
func GetUsers(c *gin.Context) {
	// Get current user context
	user, ok := helpers.GetUserFromContext(c)
	if !ok {
		return
	}

	// Parse pagination and sorting parameters
	page, pageSize, sortBy, sortDirection := helpers.GetPaginationAndSortingFromQuery(c)

	// Parse search parameter
	search := c.Query("search")

	// Parse filter parameters
	organizationFilter := c.QueryArray("organization_id")
	statuses := c.QueryArray("status")
	roleFilter := c.QueryArray("role")
	createdByFilter := c.QueryArray("created_by")

	// Create service
	service := local.NewUserService()

	// Get users based on RBAC
	userOrgRole := strings.ToLower(user.OrgRole)
	accounts, totalCount, err := service.ListUsers(userOrgRole, user.OrganizationID, page, pageSize, search, sortBy, sortDirection, organizationFilter, statuses, roleFilter, createdByFilter)
	if err != nil {
		logger.Error().
			Err(err).
			Str("user_id", user.ID).
			Str("user_org_role", userOrgRole).
			Msg("Failed to list users")

		c.JSON(http.StatusInternalServerError, response.InternalServerError("failed to list users", nil))
		return
	}

	// Check if current user has impersonate permission (from user roles or organization roles)
	canImpersonate := HasPermission(user.UserPermissions, user.OrgPermissions, "impersonate:users")

	// Enrich users with impersonation consent status if user can impersonate
	enrichedUsers := make([]gin.H, 0)
	if canImpersonate {
		impersonationService := local.NewImpersonationService()

		// Collect all user IDs for batch consent check (performance optimization)
		userIDs := make([]string, len(accounts))
		for i, account := range accounts {
			userIDs[i] = account.ID
		}

		// Batch check impersonation consent for all users (single query instead of N queries)
		consentMap, err := impersonationService.CanBeImpersonatedBatch(userIDs)
		if err != nil {
			logger.RequestLogger(c, "users").Warn().
				Err(err).
				Int("user_count", len(userIDs)).
				Msg("Failed to batch check impersonation consent, defaulting to false")
			// Initialize empty map so all users default to false
			consentMap = make(map[string]bool)
		}

		for _, account := range accounts {
			// Get consent status from batch result (defaults to false if not found)
			canBeImpersonated := consentMap[account.ID]

			// Convert account to gin.H and add impersonation field
			userMap := gin.H{
				"id":                  account.ID,
				"logto_id":            account.LogtoID,
				"username":            account.Username,
				"email":               account.Email,
				"name":                account.Name,
				"phone":               account.Phone,
				"organization":        account.Organization,
				"roles":               account.Roles,
				"custom_data":         account.CustomData,
				"created_at":          account.CreatedAt,
				"updated_at":          account.UpdatedAt,
				"logto_synced_at":     account.LogtoSyncedAt,
				"latest_login_at":     account.LatestLoginAt,
				"deleted_at":          account.DeletedAt,
				"suspended_at":        account.SuspendedAt,
				"suspended_by_org_id": account.SuspendedByOrgID,
				"created_by":          account.CreatedBy,
				"has_avatar":          account.HasAvatar,
				"can_be_impersonated": canBeImpersonated,
			}
			enrichedUsers = append(enrichedUsers, userMap)
		}
	} else {
		// For non-Owner users, just convert to gin.H without impersonation field
		for _, account := range accounts {
			userMap := gin.H{
				"id":                  account.ID,
				"logto_id":            account.LogtoID,
				"username":            account.Username,
				"email":               account.Email,
				"name":                account.Name,
				"phone":               account.Phone,
				"organization":        account.Organization,
				"roles":               account.Roles,
				"custom_data":         account.CustomData,
				"created_at":          account.CreatedAt,
				"updated_at":          account.UpdatedAt,
				"logto_synced_at":     account.LogtoSyncedAt,
				"latest_login_at":     account.LatestLoginAt,
				"deleted_at":          account.DeletedAt,
				"suspended_at":        account.SuspendedAt,
				"suspended_by_org_id": account.SuspendedByOrgID,
				"created_by":          account.CreatedBy,
				"has_avatar":          account.HasAvatar,
			}
			enrichedUsers = append(enrichedUsers, userMap)
		}
	}

	// Log the action
	logger.RequestLogger(c, "users").Info().
		Str("operation", "list_users").
		Int("page", page).
		Int("page_size", pageSize).
		Str("search", search).
		Int("total_count", totalCount).
		Int("returned_count", len(accounts)).
		Bool("can_impersonate", canImpersonate).
		Msg("Users list requested")

	// Return paginated response with enriched data
	c.JSON(http.StatusOK, response.OK("users retrieved successfully", gin.H{
		"users":      enrichedUsers,
		"pagination": helpers.BuildPaginationInfoWithSorting(page, pageSize, totalCount, sortBy, sortDirection),
	}))
}

// UpdateUser handles PUT /api/users/:id - updates a user account locally and syncs to Logto
func UpdateUser(c *gin.Context) {
	// Get user ID from URL parameter
	userID := c.Param("id")
	if userID == "" {
		c.JSON(http.StatusBadRequest, response.BadRequest("user ID required", nil))
		return
	}

	// Parse request body
	var request models.UpdateLocalUserRequest
	if err := c.ShouldBindBodyWith(&request, binding.JSON); err != nil {
		c.JSON(http.StatusBadRequest, response.ValidationBadRequestMultiple(err))
		return
	}

	// Additional validation for name and username fields - prevent empty strings
	var validationErrors []response.ValidationError

	if request.Name != nil && strings.TrimSpace(*request.Name) == "" {
		validationErrors = append(validationErrors, response.ValidationError{
			Key:     "name",
			Message: "cannot_be_empty",
		})
	}

	if request.Username != nil && strings.TrimSpace(*request.Username) == "" {
		validationErrors = append(validationErrors, response.ValidationError{
			Key:     "username",
			Message: "cannot_be_empty",
		})
	}

	if len(validationErrors) > 0 {
		c.JSON(http.StatusBadRequest, response.ValidationFailed("validation failed", validationErrors))
		return
	}

	// Get current user context
	user, ok := helpers.GetUserFromContext(c)
	if !ok {
		return
	}

	// Get current user account for RBAC validation
	repo := entities.NewLocalUserRepository()
	currentAccount, err := repo.GetByID(userID)
	if err != nil {
		if strings.Contains(err.Error(), "not found") {
			c.JSON(http.StatusNotFound, response.NotFound("user not found", nil))
			return
		}

		logger.Error().
			Err(err).
			Str("current_user_id", user.ID).
			Str("target_user_id", userID).
			Msg("Failed to get user for update validation")

		c.JSON(http.StatusInternalServerError, response.InternalServerError("failed to get user", nil))
		return
	}

	// Apply RBAC validation
	userOrgRole := strings.ToLower(user.OrgRole)
	canUpdate := false

	// Users can always update themselves (with restrictions)
	if userID == user.ID {
		canUpdate = true
		// Users can only update certain fields about themselves
		// Organization-related fields should be restricted
		if request.OrganizationID != nil || request.UserRoleIDs != nil {
			c.JSON(http.StatusForbidden, response.Forbidden("users cannot modify their own organization or role information", nil))
			return
		}
	} else {
		// Check organization-based permissions for updating other users
		targetOrgID := ""
		if currentAccount.OrganizationID != nil {
			targetOrgID = *currentAccount.OrganizationID
		}

		service := local.NewUserService()
		if canUpdateUser, reason := service.CanUpdateUser(userOrgRole, user.OrganizationID, targetOrgID); canUpdateUser {
			canUpdate = true
		} else {
			c.JSON(http.StatusForbidden, response.Forbidden("access denied: "+reason, nil))
			return
		}

		// An organization change is authorized against the DESTINATION too:
		// CanUpdateUser only proves the caller reaches the user where it is
		// now. Moving it upward or sideways would otherwise hand the user (and
		// whoever it then acts for) the destination's reach.
		if request.OrganizationID != nil && *request.OrganizationID != targetOrgID {
			if canMove, reason := service.CanMoveUserToOrganization(userOrgRole, user.OrganizationID, *request.OrganizationID); !canMove {
				logger.RequestLogger(c, "users").Warn().
					Str("operation", "user_move_denied").
					Str("target_user_id", userID).
					Str("destination_organization_id", *request.OrganizationID).
					Str("caller_organization_id", user.OrganizationID).
					Str("caller_org_role", userOrgRole).
					Msg("Organization change refused: destination outside the caller's hierarchy")
				c.JSON(http.StatusForbidden, response.Forbidden("access denied: "+reason, nil))
				return
			}
		}
	}

	if !canUpdate {
		c.JSON(http.StatusForbidden, response.Forbidden("access denied to update user", nil))
		return
	}

	// Validate that roles are not being set to empty
	if request.UserRoleIDs != nil && len(*request.UserRoleIDs) == 0 {
		c.JSON(http.StatusBadRequest, response.ValidationFailed("validation failed", []response.ValidationError{
			{Key: "user_role_ids", Message: "at least one role is required"},
		}))
		return
	}

	// Validate role assignment permissions if roles are being updated
	if request.UserRoleIDs != nil && len(*request.UserRoleIDs) > 0 {
		roleCache := cache.GetRoleNames()
		if !roleCache.IsLoaded() {
			logger.Error().
				Str("current_user_id", user.ID).
				Str("target_user_id", userID).
				Msg("Role cache not loaded - cannot validate role assignments")
			c.JSON(http.StatusInternalServerError, response.InternalServerError("role validation unavailable", nil))
			return
		}

		// Check each role being assigned
		for _, roleID := range *request.UserRoleIDs {
			// Reject unknown roles up front, exactly like the create path: an id
			// the cache cannot vouch for would otherwise skip the access-control
			// check below and fail mid-sync in Logto at best.
			if !roleCache.HasRole(roleID) {
				c.JSON(http.StatusBadRequest, response.ValidationFailed("validation failed", []response.ValidationError{
					{Key: "user_role_ids", Message: "role not found", Value: roleID},
				}))
				return
			}

			accessControl, exists := roleCache.GetAccessControl(roleID)
			if exists && accessControl.HasAccessControl {
				// This role has access control restrictions
				hasPermission := HasOrgRolePermission(user.OrgRole, accessControl.RequiredOrgRole)
				if !hasPermission {
					logger.RequestLogger(c, "users").Warn().
						Str("operation", "role_assignment_denied").
						Str("current_user_id", user.ID).
						Str("current_user_org_role", user.OrgRole).
						Str("target_user_id", userID).
						Str("role_id", roleID).
						Str("required_org_role", accessControl.RequiredOrgRole).
						Msg("User attempted to assign role without sufficient privileges")

					c.JSON(http.StatusForbidden, response.Forbidden("insufficient privileges to assign this role", map[string]interface{}{
						"role_id":           roleID,
						"required_org_role": strings.ToLower(accessControl.RequiredOrgRole),
						"current_org_role":  strings.ToLower(user.OrgRole),
					}))
					return
				}

				logger.RequestLogger(c, "users").Debug().
					Str("operation", "role_assignment_validated").
					Str("current_user_id", user.ID).
					Str("current_user_org_role", user.OrgRole).
					Str("target_user_id", userID).
					Str("role_id", roleID).
					Str("required_org_role", accessControl.RequiredOrgRole).
					Msg("Role assignment validated successfully")
			}
		}
	}

	// Create service
	service := local.NewUserService()

	// Update user
	account, err := service.UpdateUser(userID, &request, user.ID, user.OrganizationID, userOrgRole, user.UserRoles)
	if err != nil {
		logger.Error().
			Err(err).
			Str("current_user_id", user.ID).
			Str("target_user_id", userID).
			Msg("Failed to update user")

		// Check if it's a validation error from Logto
		if validationErr := getValidationError(err); validationErr != nil {
			if validationErr.StatusCode == http.StatusForbidden {
				c.JSON(http.StatusForbidden, response.Forbidden("access denied: "+validationErr.ErrorData.Errors[0].Message, nil))
				return
			}
			c.JSON(http.StatusBadRequest, response.ValidationFailed("validation failed", validationErr.ErrorData.Errors))
			return
		}

		// Default to internal server error
		c.JSON(http.StatusInternalServerError, response.InternalServerError("failed to update user", map[string]interface{}{
			"error": err.Error(),
		}))
		return
	}

	// Invalidate cached user profile (roles/permissions may have changed)
	invalidateUserProfileCache(currentAccount.LogtoID)

	// Log the action
	logger.LogBusinessOperation(c, "users", "update", "user", userID, true, nil)

	// Return success response
	c.JSON(http.StatusOK, response.OK("user updated successfully", account))
}

// DeleteUser handles DELETE /api/users/:id - soft-deletes a user account locally and syncs to Logto
func DeleteUser(c *gin.Context) {
	// Get user ID from URL parameter
	userID := c.Param("id")
	if userID == "" {
		c.JSON(http.StatusBadRequest, response.BadRequest("user ID required", nil))
		return
	}

	// Get current user context
	user, ok := helpers.GetUserFromContext(c)
	if !ok {
		return
	}

	// Users cannot delete themselves
	if userID == user.ID {
		c.JSON(http.StatusForbidden, response.Forbidden("users cannot delete their own account", nil))
		return
	}

	// Get current user account for RBAC validation
	repo := entities.NewLocalUserRepository()
	currentAccount, err := repo.GetByID(userID)
	if err != nil {
		if strings.Contains(err.Error(), "not found") {
			c.JSON(http.StatusNotFound, response.NotFound("user not found", nil))
			return
		}

		logger.Error().
			Err(err).
			Str("current_user_id", user.ID).
			Str("target_user_id", userID).
			Msg("Failed to get user for delete validation")

		c.JSON(http.StatusInternalServerError, response.InternalServerError("failed to get user", nil))
		return
	}

	// Apply RBAC validation
	targetOrgID := ""
	if currentAccount.OrganizationID != nil {
		targetOrgID = *currentAccount.OrganizationID
	}

	userOrgRole := strings.ToLower(user.OrgRole)
	service := local.NewUserService()

	if canDelete, reason := service.CanDeleteUser(userOrgRole, user.OrganizationID, targetOrgID); !canDelete {
		c.JSON(http.StatusForbidden, response.Forbidden("access denied: "+reason, nil))
		return
	}
	if denyOwnerOrgTargetWithoutOwnerRole(c, user, targetOrgID) {
		return
	}

	// Delete user
	err = service.DeleteUser(userID, user.ID, user.OrganizationID)
	if err != nil {
		logger.Error().
			Err(err).
			Str("current_user_id", user.ID).
			Str("target_user_id", userID).
			Msg("Failed to delete user")

		c.JSON(http.StatusInternalServerError, response.InternalServerError("failed to delete user", map[string]interface{}{
			"error": err.Error(),
		}))
		return
	}

	// A soft-deleted account must stop acting now: tokens issued before this
	// moment are refused by the middleware, and the next resolve sees
	// deleted_at (restore lifts both).
	if currentAccount.LogtoID != nil && *currentAccount.LogtoID != "" {
		if blErr := cache.GetTokenBlacklist().BlacklistAllUserTokens(*currentAccount.LogtoID, "user deleted"); blErr != nil {
			logger.RequestLogger(c, "users").Warn().
				Err(blErr).
				Str("operation", "blacklist_deleted_user").
				Str("user_id", userID).
				Msg("Failed to revoke tokens of deleted user")
		}
	}

	// Invalidate cached user profile
	invalidateUserProfileCache(currentAccount.LogtoID)

	// Log the action
	logger.LogBusinessOperation(c, "users", "delete", "user", userID, true, nil)

	// Return success response
	c.JSON(http.StatusOK, response.OK("user deleted successfully", nil))
}

// RestoreUser handles PATCH /api/users/:id/restore - restores a soft-deleted user
func RestoreUser(c *gin.Context) {
	userID := c.Param("id")
	if userID == "" {
		c.JSON(http.StatusBadRequest, response.BadRequest("user ID required", nil))
		return
	}

	user, ok := helpers.GetUserFromContext(c)
	if !ok {
		return
	}

	// Fetch target user to get LogtoID for cache invalidation
	repo := entities.NewLocalUserRepository()
	targetUser, _ := repo.GetByID(userID)

	service := local.NewUserService()

	err := service.RestoreUser(userID, user.ID, user.OrganizationID, strings.ToLower(user.OrgRole), user.UserRoles)
	if err != nil {
		errMsg := err.Error()

		if strings.Contains(errMsg, "not found") {
			c.JSON(http.StatusNotFound, response.NotFound("user not found", nil))
			return
		}

		if strings.Contains(errMsg, "not deleted") {
			c.JSON(http.StatusBadRequest, response.BadRequest("user is not deleted", nil))
			return
		}

		if strings.Contains(errMsg, "organization is deleted") {
			c.JSON(http.StatusBadRequest, response.BadRequest("user's organization is deleted and must be restored first", nil))
			return
		}

		if strings.Contains(errMsg, "access denied") {
			c.JSON(http.StatusForbidden, response.Forbidden("access denied to restore user", nil))
			return
		}

		logger.Error().
			Err(err).
			Str("current_user_id", user.ID).
			Str("target_user_id", userID).
			Msg("Failed to restore user")

		c.JSON(http.StatusInternalServerError, response.InternalServerError("failed to restore user", nil))
		return
	}

	// Invalidate cached user profile
	if targetUser != nil {
		invalidateUserProfileCache(targetUser.LogtoID)
	}

	logger.LogBusinessOperation(c, "users", "restore", "user", userID, true, nil)

	c.JSON(http.StatusOK, response.OK("user restored successfully", nil))
}

// DestroyUser handles DELETE /api/users/:id/destroy - permanently deletes a user
func DestroyUser(c *gin.Context) {
	userID := c.Param("id")
	if userID == "" {
		c.JSON(http.StatusBadRequest, response.BadRequest("user ID required", nil))
		return
	}

	user, ok := helpers.GetUserFromContext(c)
	if !ok {
		return
	}

	// Fetch target user to get LogtoID for cache invalidation (before destroy)
	repo := entities.NewLocalUserRepository()
	targetUser, _ := repo.GetByID(userID)

	service := local.NewUserService()

	err := service.DestroyUser(userID, user.ID, user.OrganizationID, strings.ToLower(user.OrgRole))
	if err != nil {
		errMsg := err.Error()

		if strings.Contains(errMsg, "not found") {
			c.JSON(http.StatusNotFound, response.NotFound("user not found", nil))
			return
		}

		if strings.Contains(errMsg, "access denied") {
			c.JSON(http.StatusForbidden, response.Forbidden("access denied to destroy user", nil))
			return
		}

		logger.Error().
			Err(err).
			Str("current_user_id", user.ID).
			Str("target_user_id", userID).
			Msg("Failed to destroy user")

		c.JSON(http.StatusInternalServerError, response.InternalServerError("failed to destroy user", map[string]interface{}{
			"error": errMsg,
		}))
		return
	}

	// Invalidate cached user profile
	if targetUser != nil {
		invalidateUserProfileCache(targetUser.LogtoID)
	}

	logger.LogBusinessOperation(c, "users", "destroy", "user", userID, true, nil)

	c.JSON(http.StatusOK, response.OK("user permanently destroyed", nil))
}

// SuspendUser handles PATCH /api/users/:id/suspend - suspends a user
func SuspendUser(c *gin.Context) {
	// Get user ID from URL parameter
	userID := c.Param("id")
	if userID == "" {
		c.JSON(http.StatusBadRequest, response.BadRequest("user ID required", nil))
		return
	}

	// Get current user context
	user, ok := helpers.GetUserFromContext(c)
	if !ok {
		return
	}

	// Users cannot suspend themselves
	if userID == user.ID {
		c.JSON(http.StatusForbidden, response.Forbidden("users cannot suspend themselves", nil))
		return
	}

	// Get target user to check permissions
	userRepo := entities.NewLocalUserRepository()
	targetUser, err := userRepo.GetByID(userID)
	if err != nil {
		if strings.Contains(err.Error(), "not found") {
			c.JSON(http.StatusNotFound, response.NotFound("user not found", nil))
		} else {
			logger.Logger.Error().
				Str("component", "user-handler").
				Str("action", "get-target-user").
				Str("user_id", userID).
				Err(err).
				Msg("Failed to get target user for suspension")
			c.JSON(http.StatusInternalServerError, response.InternalServerError("failed to get user", nil))
		}
		return
	}

	// Permission validation for suspension
	userService := local.NewUserService()
	userOrgRole := strings.ToLower(user.OrgRole)
	targetOrgID := ""
	if targetUser.OrganizationID != nil {
		targetOrgID = *targetUser.OrganizationID
	}
	canSuspend, reason := userService.CanSuspendUser(userOrgRole, user.OrganizationID, targetOrgID)
	if !canSuspend {
		c.JSON(http.StatusForbidden, response.Forbidden(reason, nil))
		return
	}
	if denyOwnerOrgTargetWithoutOwnerRole(c, user, targetOrgID) {
		return
	}

	// Suspend user
	err = userService.SuspendUser(userID, user.ID, user.OrganizationID)
	if err != nil {
		if strings.Contains(err.Error(), "not found or already suspended") {
			c.JSON(http.StatusBadRequest, response.BadRequest("user not found or already suspended", nil))
		} else {
			logger.Logger.Error().
				Str("component", "user-handler").
				Str("action", "suspend-user").
				Str("user_id", userID).
				Str("suspended_by", user.ID).
				Err(err).
				Msg("Failed to suspend user")
			c.JSON(http.StatusInternalServerError, response.InternalServerError("failed to suspend user", nil))
		}
		return
	}

	// Blacklist all user tokens when suspended
	blacklist := cache.GetTokenBlacklist()
	blacklistErr := blacklist.BlacklistAllUserTokens(userID, "user suspended by administrator")
	if blacklistErr != nil {
		logger.RequestLogger(c, "users").Warn().
			Err(blacklistErr).
			Str("operation", "blacklist_suspended_user").
			Str("user_id", userID).
			Str("suspended_by", user.ID).
			Msg("Failed to blacklist suspended user tokens - user suspended but tokens still valid")
		// Don't fail the suspension if blacklist fails, just log warning
	} else {
		logger.RequestLogger(c, "users").Info().
			Str("operation", "tokens_blacklisted").
			Str("user_id", userID).
			Str("suspended_by", user.ID).
			Msg("All user tokens blacklisted due to suspension")
	}

	// Invalidate cached user profile
	invalidateUserProfileCache(targetUser.LogtoID)

	// Log the action
	logger.LogBusinessOperation(c, "users", "suspend", "user", userID, true, nil)

	// Return success response
	c.JSON(http.StatusOK, response.OK("user suspended successfully", nil))
}

// ReactivateUser handles PATCH /api/users/:id/reactivate - reactivates a suspended user
func ReactivateUser(c *gin.Context) {
	// Get user ID from URL parameter
	userID := c.Param("id")
	if userID == "" {
		c.JSON(http.StatusBadRequest, response.BadRequest("user ID required", nil))
		return
	}

	// Get current user context
	user, ok := helpers.GetUserFromContext(c)
	if !ok {
		return
	}

	// Get target user to check permissions
	userRepo := entities.NewLocalUserRepository()
	targetUser, err := userRepo.GetByID(userID)
	if err != nil {
		if strings.Contains(err.Error(), "not found") {
			c.JSON(http.StatusNotFound, response.NotFound("user not found", nil))
		} else {
			logger.Logger.Error().
				Str("component", "user-handler").
				Str("action", "get-target-user").
				Str("user_id", userID).
				Err(err).
				Msg("Failed to get target user for reactivation")
			c.JSON(http.StatusInternalServerError, response.InternalServerError("failed to get user", nil))
		}
		return
	}

	// Permission validation for reactivation (same as suspension)
	userService := local.NewUserService()
	userOrgRole := strings.ToLower(user.OrgRole)
	targetOrgID := ""
	if targetUser.OrganizationID != nil {
		targetOrgID = *targetUser.OrganizationID
	}
	canSuspend, reason := userService.CanSuspendUser(userOrgRole, user.OrganizationID, targetOrgID)
	if !canSuspend {
		c.JSON(http.StatusForbidden, response.Forbidden(reason, nil))
		return
	}
	if denyOwnerOrgTargetWithoutOwnerRole(c, user, targetOrgID) {
		return
	}

	// If user was cascade-suspended, check authority over the suspending org
	if targetUser.SuspendedByOrgID != nil && *targetUser.SuspendedByOrgID != "" {
		canReactivate, cascadeReason := userService.CanSuspendUser(userOrgRole, user.OrganizationID, *targetUser.SuspendedByOrgID)
		if !canReactivate {
			c.JSON(http.StatusForbidden, response.Forbidden(
				fmt.Sprintf("user was suspended by organization cascade, %s", cascadeReason), nil))
			return
		}
	}

	// Reactivate user
	err = userService.ReactivateUser(userID, user.ID, user.OrganizationID)
	if err != nil {
		if strings.Contains(err.Error(), "not found or not suspended") {
			c.JSON(http.StatusBadRequest, response.BadRequest("user not found or not suspended", nil))
		} else {
			logger.Logger.Error().
				Str("component", "user-handler").
				Str("action", "reactivate-user").
				Str("user_id", userID).
				Str("reactivated_by", user.ID).
				Err(err).
				Msg("Failed to reactivate user")
			c.JSON(http.StatusInternalServerError, response.InternalServerError("failed to reactivate user", nil))
		}
		return
	}

	// Remove user from token blacklist when reactivated
	blacklist := cache.GetTokenBlacklist()
	blacklistErr := blacklist.RemoveUserFromBlacklist(userID)
	if blacklistErr != nil {
		logger.RequestLogger(c, "users").Warn().
			Err(blacklistErr).
			Str("operation", "remove_user_from_blacklist").
			Str("user_id", userID).
			Str("reactivated_by", user.ID).
			Msg("Failed to remove user from token blacklist - user reactivated but old tokens still blocked")
		// Don't fail the reactivation if blacklist removal fails, just log warning
	} else {
		logger.RequestLogger(c, "users").Info().
			Str("operation", "user_removed_from_blacklist").
			Str("user_id", userID).
			Str("reactivated_by", user.ID).
			Msg("User removed from token blacklist due to reactivation")
	}

	// Invalidate cached user profile
	invalidateUserProfileCache(targetUser.LogtoID)

	// Log the action
	logger.LogBusinessOperation(c, "users", "reactivate", "user", userID, true, nil)

	// Return success response
	c.JSON(http.StatusOK, response.OK("user reactivated successfully", nil))
}

// ResetUserPassword handles PATCH /api/users/:id/password - resets user password
func ResetUserPassword(c *gin.Context) {
	// Get user ID from URL parameter
	userID := c.Param("id")
	if userID == "" {
		c.JSON(http.StatusBadRequest, response.BadRequest("user ID required", nil))
		return
	}

	// Parse request body for password (as per OpenAPI spec)
	var request struct {
		Password string `json:"password"`
	}
	if err := c.ShouldBindBodyWith(&request, binding.JSON); err != nil {
		c.JSON(http.StatusBadRequest, response.ValidationBadRequestMultiple(err))
		return
	}

	// Validate password using our secure validator
	isValid, errorCodes := helpers.ValidatePasswordStrength(request.Password)
	if !isValid {
		c.JSON(http.StatusBadRequest, response.PasswordValidationBadRequest(errorCodes))
		return
	}

	// Get current user context
	user, ok := helpers.GetUserFromContext(c)
	if !ok {
		return
	}

	// Get target user account for RBAC validation
	repo := entities.NewLocalUserRepository()
	targetAccount, err := repo.GetByID(userID)
	if err != nil {
		if strings.Contains(err.Error(), "not found") {
			c.JSON(http.StatusNotFound, response.NotFound("user not found", nil))
			return
		}

		logger.Error().
			Err(err).
			Str("current_user_id", user.ID).
			Str("target_user_id", userID).
			Msg("Failed to get user for password reset")

		c.JSON(http.StatusInternalServerError, response.InternalServerError("failed to get user", nil))
		return
	}

	// Apply RBAC validation - use the same hierarchical logic as CanUpdateUser
	userOrgRole := strings.ToLower(user.OrgRole)
	canReset := false

	// Create service for hierarchical validation and password reset
	service := local.NewUserService()

	// Users can reset their own password
	if userID == user.ID {
		canReset = true
	} else {
		// Check hierarchical permissions for resetting other users' passwords
		targetOrgID := ""
		if targetAccount.OrganizationID != nil {
			targetOrgID = *targetAccount.OrganizationID
		}

		canReset, _ = service.CanUpdateUser(userOrgRole, user.OrganizationID, targetOrgID)

		// Resetting a colleague's password is an account takeover: for users of
		// the Owner organization it stays an Owner-role exclusive, like every
		// other mutation of that membership.
		if canReset && denyOwnerOrgTargetWithoutOwnerRole(c, user, targetOrgID) {
			return
		}
	}

	if !canReset {
		c.JSON(http.StatusForbidden, response.Forbidden("access denied to reset password", nil))
		return
	}

	// Check if user is synced to Logto
	if targetAccount.LogtoID == nil {
		c.JSON(http.StatusBadRequest, response.BadRequest("user not synced to Logto", nil))
		return
	}

	// Reset password using Logto ID (service already created above)
	err = service.ResetUserPassword(*targetAccount.LogtoID, request.Password)
	if err != nil {
		logger.Error().
			Err(err).
			Str("current_user_id", user.ID).
			Str("target_user_id", userID).
			Str("logto_user_id", *targetAccount.LogtoID).
			Msg("Failed to reset user password")

		// Check if it's a validation error from Logto (same as other endpoints)
		if validationErr := getValidationError(err); validationErr != nil {
			c.JSON(http.StatusBadRequest, response.ValidationFailed("validation failed", validationErr.ErrorData.Errors))
			return
		}

		// Default to internal server error for non-validation errors
		c.JSON(http.StatusInternalServerError, response.InternalServerError("failed to reset password", map[string]interface{}{
			"error": err.Error(),
		}))
		return
	}

	// Log the action
	logger.LogBusinessOperation(c, "users", "password_reset", "user", userID, true, nil)

	// Return success response
	c.JSON(http.StatusOK, response.OK("password reset successfully", nil))
}
